### PR TITLE
Update VB Sample for VS 2019 and Fix 'score' bug

### PR DESCRIPTION
**Pull request by geekcyclist**

### CODE REVIEW

**Comment by geekcyclist** [comment]
My original goal was to fix the "bug" I noticed where 'score' was used rather than 'acceptScore', but the project wouldn't build in VS 2019, so I decided to update it, and add the constants and comments for clarity. Feel free to reject if you want, but at the least the score => acceptScore should be fixed in this sample. - Gary Ray

**Comment by steveoh** [comment]
This is a 2019 project and you can install 2019 community for free. It is on my list to review this and Gary and I have spoken offline about it. The resx file from what I can tell is unused and should be removed but I would like to do a more thorough review before commenting much more.

**Comment by geekcyclist** [comment]
Interesting... A missing resx file message is part of what prompted me to try and upgrade the project. I show one committed in https://github.com/geekcyclist/GeocodingSample/commit/822153d7 and it shows in my most recent update on github https://github.com/geekcyclist/GeocodingSample/tree/master/VB/My%20Project

**Comment by steveoh** [comment]
Thanks for the accept score fix! I went a different direction and hopefully simplified the project to use .net core and no external dependencies. It all looks pretty much the same except a few properties on the system.text.json serializer that newtonsoft had by default.

**Pull request closed without merging**
